"""empty message

Revision ID: 0bc90639a26f
Revises: 7e8a8167713f
Create Date: 2021-10-17 23:32:36.371840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc90639a26f'
down_revision = '7e8a8167713f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('username', sa.String(length=80), nullable=False))
    op.create_foreign_key(None, 'articles', 'users', ['username'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'username')
    # ### end Alembic commands ###
