"""added to post model

Revision ID: 5601729e84f5
Revises: 5a2e79cbbf89
Create Date: 2021-10-15 12:59:32.134212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5601729e84f5'
down_revision = '5a2e79cbbf89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'ingredients')
    op.drop_column('posts', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('name', sa.VARCHAR(length=280), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('ingredients', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
