"""<some message>

Revision ID: 584a5121a801
Revises: 36b374043d98
Create Date: 2021-10-14 12:57:27.681602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584a5121a801'
down_revision = '36b374043d98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
