"""added to post model

Revision ID: 5a2e79cbbf89
Revises: 584a5121a801
Create Date: 2021-10-15 11:08:58.300157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a2e79cbbf89'
down_revision = '584a5121a801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('name', sa.String(length=280), nullable=True))
    op.add_column('posts', sa.Column('ingredients', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'ingredients')
    op.drop_column('posts', 'name')
    # ### end Alembic commands ###
